import React, { useCallback, useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { Button, Card, Field, Notice, Page, SectionTitle } from '../../../../components/UI';
import RemoteSelect from '../../../../components/RemoteSelect';
import { MoneyText } from '../../../../components/OperationalUI';
import { useAuth } from '../../../../context/AuthContext';
import { acceptQuotation, cancelQuotation, convertQuotation, getQuotation, rejectQuotation, sendQuotation, updateQuotation } from '../../../../services/operationalService';
import { hasPermission } from '../../../../services/permissions';
import { userMessage } from '../../../../api/client';
import colors from '../../../../theme/colors';

export default function QuotationDetailScreen() {
  const { id } = useLocalSearchParams(); const { request, user } = useAuth(); const [quote, setQuote] = useState(null); const [error, setError] = useState(null); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [customerId, setCustomerId] = useState(''); const [items, setItems] = useState([]);
  const load = useCallback(async () => { setError(null); try { const result = await getQuotation(request, id); setQuote(result.data); setCustomerId(result.data.customerId); setItems(result.data.items.map(item => ({ productId: item.productId, warehouseId: item.warehouseId, quantity: String(item.quantity), unitPrice: String(item.unitPrice), taxRate: String(item.taxRate), product: null }))); } catch (e) { setError(e); } }, [request, id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  async function run(operation) { setError(null); try { const result = await operation(request, id); if (result.data?.quotation) { setQuote(result.data.quotation); Alert.alert('Venta en borrador creada', result.data.sale.folio); } else setQuote(result.data); } catch (e) { setError(e); } }
  async function save() { setSaving(true); try { const result = await updateQuotation(request, id, { customerId, items: items.map(({ productId, warehouseId, quantity, unitPrice, taxRate }) => ({ productId, warehouseId, quantity: Number(quantity), unitPrice: Number(unitPrice), taxRate: Number(taxRate) })) }); setQuote(result.data); setEditing(false); } catch (e) { setError(e); } finally { setSaving(false); } }
  if (error && !quote) return <Page><Notice tone="error">{userMessage(error)}</Notice><Button title="Reintentar" onPress={load}/></Page>;
  if (!quote) return <Page><Text>Cargando cotización…</Text></Page>;
  return <Page keyboard><SectionTitle title={quote.folio}/><Notice>Estado: {quote.status} · Cliente: {quote.customer?.name || quote.customerId}</Notice>
    {editing ? <><Card><RemoteSelect label="Cliente" endpoint="/api/clients" value={customerId} onChange={setCustomerId} required/></Card>{items.map((item, index) => <Card key={index}><SectionTitle title={`Partida ${index + 1}`} action={items.length > 1 ? <Button title="Quitar" variant="danger" onPress={() => setItems(xs => xs.filter((_, n) => n !== index))}/> : null}/><RemoteSelect label="Producto" endpoint="/api/products" value={item.productId} onChange={(productId, product) => setItems(xs => xs.map((v, n) => n === index ? { ...v, productId, product, unitPrice: String(product?.salePrice || '') } : v))} required/><RemoteSelect label="Almacén" endpoint="/api/warehouses" value={item.warehouseId} onChange={warehouseId => setItems(xs => xs.map((v, n) => n === index ? { ...v, warehouseId } : v))} required/><Field label="Cantidad" value={item.quantity} keyboardType="decimal-pad" onChangeText={quantity => setItems(xs => xs.map((v, n) => n === index ? { ...v, quantity } : v))}/><Field label="Precio unitario" value={item.unitPrice} keyboardType="decimal-pad" onChangeText={unitPrice => setItems(xs => xs.map((v, n) => n === index ? { ...v, unitPrice } : v))}/><Field label="Impuesto %" value={item.taxRate} keyboardType="decimal-pad" onChangeText={taxRate => setItems(xs => xs.map((v, n) => n === index ? { ...v, taxRate } : v))}/></Card>)}<Button title="Agregar partida" variant="secondary" onPress={() => setItems(xs => [...xs, { productId: '', warehouseId: '', quantity: '1', unitPrice: '', taxRate: '0' }])}/><Button title="Guardar cambios" loading={saving} onPress={save}/><Button title="Dejar de editar" variant="secondary" onPress={() => setEditing(false)}/></> : <>
      <Card><SectionTitle title="Partidas"/>{quote.items.map((item, i) => <View key={i} style={{ gap: 4, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: 10 }}><Text style={{ color: colors.ink, fontWeight: '700' }}>{item.productNameSnapshot}</Text><Text style={{ color: colors.inkMuted }}>{item.quantity} × {Number(item.unitPrice).toLocaleString('es-MX', { style: 'currency', currency: 'MXN' })} · {item.warehouse?.name || 'Almacén'}</Text></View>)}<MoneyText value={quote.total} style={{ fontSize: 21 }}/></Card>
      {quote.status === 'draft' && hasPermission(user, 'sales.update') ? <Button title="Editar borrador" variant="secondary" onPress={() => setEditing(true)}/> : null}
      {quote.status === 'draft' && hasPermission(user, 'sales.create') ? <Button title="Enviar" onPress={() => run(sendQuotation)}/> : null}
      {quote.status === 'sent' && hasPermission(user, 'sales.update') ? <><Button title="Aceptar" onPress={() => run(acceptQuotation)}/><Button title="Rechazar" variant="secondary" onPress={() => run(rejectQuotation)}/></> : null}
      {quote.status === 'draft' && hasPermission(user, 'sales.cancel') ? <Button title="Cancelar cotización" variant="danger" onPress={() => Alert.alert('Cancelar cotización', '¿Deseas cancelar esta cotización?', [{ text: 'Volver', style: 'cancel' }, { text: 'Cancelar', style: 'destructive', onPress: () => run(cancelQuotation) }])}/> : null}
      {quote.status === 'accepted' && hasPermission(user, 'sales.create') ? <Button title="Convertir a venta" onPress={() => Alert.alert('Convertir cotización', 'Se creará una venta en borrador. El inventario no se modificará hasta confirmar la venta.', [{ text: 'Volver', style: 'cancel' }, { text: 'Convertir', onPress: () => run(convertQuotation) }])}/> : null}
    </>}{error ? <Notice tone="error">{userMessage(error)}</Notice> : null}<Button title="Volver" variant="secondary" onPress={() => router.back()}/>
  </Page>;
}
